AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  BookTableCors:
    Type: AWS::Serverless::SimpleTable
  BooksCors:
    Type: "AWS::Serverless::Function"
    Properties:
      Runtime: nodejs8.10
      Handler: books.handler
      CodeUri: ./api
      Environment:
        Variables:
          TABLE_NAME: !Ref BookTableCors
      Policies: AmazonDynamoDBFullAccess
      Events:
        AddBook:
          Type: Api
          Properties:
            Path: /books
            Method: post
        ListBooks:
          Type: Api
          Properties:
            Path: /books
            Method: get
        Book:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: any
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"