AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Api:
    Cors: AllowMethods:"'*'" AllowHeaders:"'*'" AllowOrigin:"'*'"
Resources:
  BookTableCors:
    Type: AWS::Serverless::SimpleTable
  BooksCors:
    Properties:
      CodeUri: s3://artifacts-for-lambda-ddotx/ac84681befe8c838ccf5e074cab9156a
      Environment:
        Variables:
          TABLE_NAME:
            Ref: BookTableCors
      Events:
        AddBook:
          Properties:
            Method: post
            Path: /books
          Type: Api
        Book:
          Properties:
            Method: any
            Path: /books/{id}
          Type: Api
        ListBooks:
          Properties:
            Method: get
            Path: /books
          Type: Api
      Handler: books.handler
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
